/**
 * Turns the full-size originals in assets/gallery-src/ into web-sized
 * derivatives in public/gallery/, and writes src/data/gallery.js.
 *
 * The originals are ~8.6MB and gitignored — they never ship. Only the
 * derivatives are committed.
 *
 * Run with `npm run gallery` after adding or removing photos.
 */
import sharp from 'sharp'
import { mkdir, readdir, rm, stat, writeFile } from 'node:fs/promises'
import { existsSync } from 'node:fs'
import path from 'node:path'

const SRC = 'assets/gallery-src'
const OUT = 'public/gallery'
const MANIFEST = 'src/data/gallery.js'

// Two sizes: a tile for the grid, and a larger one fetched only when the
// lightbox opens. No point shipping 1440px to a 300px-wide column.
const THUMB = { width: 500, quality: 75 }
const FULL = { width: 1400, quality: 78 }

if (!existsSync(SRC)) {
  console.error(`No ${SRC}/ — nothing to build.`)
  process.exit(1)
}

// Rebuild from scratch so deleting an original also drops its derivatives.
await rm(OUT, { recursive: true, force: true })
await mkdir(OUT, { recursive: true })

// A leading underscore keeps a file in the source folder but out of the
// gallery — used for the profile photo, which belongs in the sidebar only.
const files = (await readdir(SRC))
  .filter((f) => /\.(jpe?g|png|webp)$/i.test(f) && !f.startsWith('_'))
  .sort()

if (files.length === 0) {
  console.error(`No images in ${SRC}/.`)
  process.exit(1)
}

const entries = []
let srcBytes = 0
let outBytes = 0

for (const [i, file] of files.entries()) {
  const src = path.join(SRC, file)
  const image = sharp(src)
  const meta = await image.metadata()

  // Instagram exports carry no meaningful basename, so number them by sort
  // order — stable as long as filenames don't change.
  const id = `p${String(i + 1).padStart(2, '0')}`

  const thumbName = `${id}-thumb.webp`
  const fullName = `${id}-full.webp`

  const thumb = await sharp(src)
    .resize({ width: THUMB.width, withoutEnlargement: true })
    .webp({ quality: THUMB.quality })
    .toFile(path.join(OUT, thumbName))

  const full = await sharp(src)
    .resize({ width: FULL.width, withoutEnlargement: true })
    .webp({ quality: FULL.quality })
    .toFile(path.join(OUT, fullName))

  srcBytes += (await stat(src)).size
  outBytes += thumb.size + full.size

  entries.push({
    id,
    thumb: `gallery/${thumbName}`,
    full: `gallery/${fullName}`,
    // The original's dimensions, so the grid can reserve exact space and
    // nothing shifts as thumbnails decode.
    width: meta.width,
    height: meta.height,
  })
}

const body = `// GENERATED by scripts/build-gallery.mjs — do not edit by hand.
// Run \`npm run gallery\` to regenerate after changing assets/gallery-src/.
//
// Paths are relative so they resolve under the /Prateeek73/ base path; the
// Gallery page prefixes them with import.meta.env.BASE_URL.
export const gallery = ${JSON.stringify(entries, null, 2)}
`

await writeFile(MANIFEST, body)

const mb = (n) => (n / 1024 / 1024).toFixed(1)
console.log(`${entries.length} photos`)
console.log(`  originals   ${mb(srcBytes)} MB  (not shipped)`)
console.log(`  derivatives ${mb(outBytes)} MB  -> ${OUT}/`)
console.log(`  manifest    ${MANIFEST}`)
